// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {company} from '../models';
import {auth} from '../models';

export function GetCompanies():Promise<Array<company.Company>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function Logout(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ValidateSession(arg1:string,arg2:string):Promise<auth.User>;
