-- Seed script to populate lookup table for any new client

PRAGMA foreign_keys = OFF;  -- temporarily disable FK checks
BEGIN TRANSACTION;

-- 1) Gas types
INSERT INTO lookup(domain, code, description) VALUES
  ('gas','ethane',   'Ethane'),
  ('gas','propane',  'Propane'),
  ('gas','butane',   'Butane'),
  ('gas','isobutane','Isobutane'),
  ('gas','pentane',  'Pentane')
;

-- 2) Well statuses
INSERT INTO lookup(domain, code, description) VALUES
  ('status','A','Active'),
  ('status','B','Producing after being shut-in in 2023 (must include date well started producing again)'),
  ('status','C','Coal Bed Methane'),
  ('status','E','Enhanced'),
  ('status','F','Flat Rate (Royalties paid when there was no working interest)'),
  ('status','H','Home-Use (ALL Gas goes to a home(s), no oil, gas, or NGLs sold; must include recipient(s))'),
  ('status','L','Horizontal Other Than Marcellus'),
  ('status','M','Marcellus Vertical'),
  ('status','P','Plugged'),
  ('status','S','Shut-In'),
  ('status','Z','Marcellus Horizontal')
;

-- 3) Formations
INSERT INTO lookup(domain, code, description) VALUES
  ('formation','01','Oriskany'),
  ('formation','02','Huron, Rhinestreet'),
  ('formation','03','Devonian Shale'),
  ('formation','04','Huron'),
  ('formation','05','Huron, Shales above Huron'),
  ('formation','06','Huron, Berea'),
  ('formation','07','Berea, Devonian Shale'),
  ('formation','08','Berea'),
  ('formation','09','Any formation not on list'),
  ('formation','10','Unknown'),
  ('formation','11','Gordon'),
  ('formation','12','Alexander, Benson'),
  ('formation','13','Alexander, Benson, Riley'),
  ('formation','14','Benson'),
  ('formation','15','Benson, Riley'),
  ('formation','16','Benson, Balltown+'),
  ('formation','17','Gordon +'),
  ('formation','18','Big Injun'),
  ('formation','19','Big Injun, Big Lime'),
  ('formation','20','Benson +'),
  ('formation','21','Benson, Fifth'),
  ('formation','22','Big Lime'),
  ('formation','23','Big Lime, Maxton'),
  ('formation','24','Big Lime, Ravencliff'),
  ('formation','25','Berea +'),
  ('formation','26','Ravencliff'),
  ('formation','27','Huron, Shales above Huron'),
  ('formation','28','Weir'),
  ('formation','29','Weir +'),
  ('formation','30','Weir, Big Lime'),
  ('formation','31','Devonian Shales +'),
  ('formation','32','Brallier +'),
  ('formation','33','Elk, Benson'),
  ('formation','34','Elk, Benson, Riley'),
  ('formation','35','Elk, Benson, Riley +'),
  ('formation','36','Elk, Benson, Balltown'),
  ('formation','37','Elk, Alexander, Benson'),
  ('formation','38','Elk, Alexander, Benson +'),
  ('formation','39','Hunterville'),
  ('formation','40','Fox, Haverty'),
  ('formation','42','Maxton, Ravencliff'),
  ('formation','43','Berea, Big Lime'),
  ('formation','44','Rhinestreet, Huron, Shallow Shale'),
  ('formation','45','Devonian Shale, Pocono'),
  ('formation','46','Pocono'),
  ('formation','47','Alexander, Riley, (No Benson)'),
  ('formation','48','Rhinestreet, Alexander, Benson, Riley'),
  ('formation','49','Weir, Squaw, Big Injun'),
  ('formation','50','Rhinestreet'),
  ('formation','51','Rhinestreet +'),
  ('formation','52','All Upper Devonian (Undiv)'),
  ('formation','53','Huron, Chemung'),
  ('formation','54','Huron, Hampshire, Pocono'),
  ('formation','55','Upper Devonian (Above Huron)'),
  ('formation','56','Chemung Sands= Riley, Bradford, Balltown, Speechley, Warren (No Benson or Alexander)'),
  ('formation','57','Alexander, Benson, Balltown'),
  ('formation','58','Alexander'),
  ('formation','59','Alexander +'),
  ('formation','60','Alexander, Benson, Riley +'),
  ('formation','61','Balltown'),
  ('formation','62','Balltown, Speechley'),
  ('formation','63','Balltown, Speechley +'),
  ('formation','64','Benson, Balltown, Speechley'),
  ('formation','65','Benson, Bradford'),
  ('formation','66','Benson, Balltown'),
  ('formation','67','Benson, Riley +'),
  ('formation','68','Benson, Speechley'),
  ('formation','69','Brallier, Elk'),
  ('formation','70','Brallier'),
  ('formation','71','Deeper/Onondaga or Oriskany/Helderberg'),
  ('formation','72','Elk, Alexander'),
  ('formation','73','Elk, Benson +'),
  ('formation','74','Elk'),
  ('formation','75','Elk, Riley'),
  ('formation','76','Fox +'),
  ('formation','77','Haverty, Elk, Benson (No Alexander)'),
  ('formation','78','Haverty'),
  ('formation','79','Riley'),
  ('formation','80','Speechley'),
  ('formation','81','Alexander, Benson, Speechley'),
  ('formation','82','Haverty, Elk, Alexander'),
  ('formation','83','Huron Oil'),
  ('formation','84','Big Injun, Oil'),
  ('formation','85','Fifth, Oil'),
  ('formation','87','Bayard All'),
  ('formation','88','Fifth'),
  ('formation','89','Fifth +'),
  ('formation','90','Gordon, Injun All'),
  ('formation','91','Squaw'),
  ('formation','92','Injun +'),
  ('formation','93','4th Sand'),
  ('formation','94','50 Foot'),
  ('formation','95','Injun/Weir'),
  ('formation','96','Maxton'),
  ('formation','97','Coalbed Methane (Vertical)'),
  ('formation','98','Coalbed Methane (Horizontal)'),
  ('formation','109','Trenton/Deeper'),
  ('formation','110','Marcellus')
;

COMMIT;
PRAGMA foreign_keys = ON;