// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuditBankReconciliation(arg1) {
  return window['go']['main']['App']['AuditBankReconciliation'](arg1);
}

export function AuditCheckBatches(arg1) {
  return window['go']['main']['App']['AuditCheckBatches'](arg1);
}

export function AuditSingleBankAccount(arg1, arg2) {
  return window['go']['main']['App']['AuditSingleBankAccount'](arg1, arg2);
}

export function ClearMatchesAndRerun(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClearMatchesAndRerun'](arg1, arg2, arg3);
}

export function CommitReconciliation(arg1, arg2) {
  return window['go']['main']['App']['CommitReconciliation'](arg1, arg2);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteBankStatement(arg1, arg2) {
  return window['go']['main']['App']['DeleteBankStatement'](arg1, arg2);
}

export function DeleteReconciliationDraft(arg1, arg2) {
  return window['go']['main']['App']['DeleteReconciliationDraft'](arg1, arg2);
}

export function ExportNetDistribution(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportNetDistribution'](arg1, arg2, arg3);
}

export function GetAPIKey(arg1) {
  return window['go']['main']['App']['GetAPIKey'](arg1);
}

export function GetAccountBalance(arg1, arg2) {
  return window['go']['main']['App']['GetAccountBalance'](arg1, arg2);
}

export function GetAllRoles() {
  return window['go']['main']['App']['GetAllRoles']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBalanceHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBalanceHistory'](arg1, arg2, arg3);
}

export function GetBankAccounts(arg1) {
  return window['go']['main']['App']['GetBankAccounts'](arg1);
}

export function GetBankAccountsForAudit(arg1) {
  return window['go']['main']['App']['GetBankAccountsForAudit'](arg1);
}

export function GetBankTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBankTransactions'](arg1, arg2, arg3);
}

export function GetCachedBalances(arg1) {
  return window['go']['main']['App']['GetCachedBalances'](arg1);
}

export function GetClosingStatus(arg1) {
  return window['go']['main']['App']['GetClosingStatus'](arg1);
}

export function GetCompanies() {
  return window['go']['main']['App']['GetCompanies']();
}

export function GetCompanyInfo(arg1) {
  return window['go']['main']['App']['GetCompanyInfo'](arg1);
}

export function GetCompanyList() {
  return window['go']['main']['App']['GetCompanyList']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDBFFiles(arg1) {
  return window['go']['main']['App']['GetDBFFiles'](arg1);
}

export function GetDBFTableData(arg1, arg2) {
  return window['go']['main']['App']['GetDBFTableData'](arg1, arg2);
}

export function GetDBFTableDataPaged(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetDBFTableDataPaged'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function GetLastReconciliation(arg1, arg2) {
  return window['go']['main']['App']['GetLastReconciliation'](arg1, arg2);
}

export function GetMatchedTransactions(arg1, arg2) {
  return window['go']['main']['App']['GetMatchedTransactions'](arg1, arg2);
}

export function GetNetDistributionStatus(arg1, arg2) {
  return window['go']['main']['App']['GetNetDistributionStatus'](arg1, arg2);
}

export function GetOutstandingChecks(arg1, arg2) {
  return window['go']['main']['App']['GetOutstandingChecks'](arg1, arg2);
}

export function GetRecentBankStatements(arg1, arg2) {
  return window['go']['main']['App']['GetRecentBankStatements'](arg1, arg2);
}

export function GetReconciliationDraft(arg1, arg2) {
  return window['go']['main']['App']['GetReconciliationDraft'](arg1, arg2);
}

export function GetReconciliationHistory(arg1, arg2) {
  return window['go']['main']['App']['GetReconciliationHistory'](arg1, arg2);
}

export function GetTableList(arg1) {
  return window['go']['main']['App']['GetTableList'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportBankStatement(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportBankStatement'](arg1, arg2, arg3);
}

export function InitializeCompanyDatabase(arg1) {
  return window['go']['main']['App']['InitializeCompanyDatabase'](arg1);
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function ManualMatchTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManualMatchTransaction'](arg1, arg2, arg3);
}

export function MigrateReconciliationData(arg1) {
  return window['go']['main']['App']['MigrateReconciliationData'](arg1);
}

export function RefreshAccountBalance(arg1, arg2) {
  return window['go']['main']['App']['RefreshAccountBalance'](arg1, arg2);
}

export function RefreshAllBalances(arg1) {
  return window['go']['main']['App']['RefreshAllBalances'](arg1);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function ReopenPeriod(arg1, arg2) {
  return window['go']['main']['App']['ReopenPeriod'](arg1, arg2);
}

export function RetryMatching(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryMatching'](arg1, arg2, arg3);
}

export function RunClosingProcess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunClosingProcess'](arg1, arg2, arg3, arg4);
}

export function RunMatching(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunMatching'](arg1, arg2, arg3);
}

export function RunNetDistribution(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunNetDistribution'](arg1, arg2, arg3, arg4);
}

export function SaveReconciliationDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveReconciliationDraft'](arg1, arg2);
}

export function SearchDBFTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchDBFTable'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function TestAPIKey(arg1, arg2) {
  return window['go']['main']['App']['TestAPIKey'](arg1, arg2);
}

export function TestDatabaseQuery(arg1, arg2) {
  return window['go']['main']['App']['TestDatabaseQuery'](arg1, arg2);
}

export function TestLogging() {
  return window['go']['main']['App']['TestLogging']();
}

export function TestOLEConnection() {
  return window['go']['main']['App']['TestOLEConnection']();
}

export function UnmatchTransaction(arg1) {
  return window['go']['main']['App']['UnmatchTransaction'](arg1);
}

export function UpdateCompanyInfo(arg1) {
  return window['go']['main']['App']['UpdateCompanyInfo'](arg1);
}

export function UpdateDBFRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDBFRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateUserRole(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserRole'](arg1, arg2);
}

export function UpdateUserStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserStatus'](arg1, arg2);
}

export function ValidateSession(arg1, arg2) {
  return window['go']['main']['App']['ValidateSession'](arg1, arg2);
}
