// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {company} from '../models';

export function AdminResetPassword(arg1:number,arg2:string):Promise<void>;

export function AnalyzeGLBalancesByYear(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AuditBankReconciliation(arg1:string):Promise<Record<string, any>>;

export function AuditCheckBatches(arg1:string):Promise<Record<string, any>>;

export function AuditCheckGLMatching(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function AuditDuplicateCIDCHEC(arg1:string):Promise<Record<string, any>>;

export function AuditPayeeCIDVerification(arg1:string):Promise<Record<string, any>>;

export function AuditSingleBankAccount(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AuditVoidChecks(arg1:string):Promise<Record<string, any>>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CheckGLPeriodFields(arg1:string):Promise<Record<string, any>>;

export function CheckOwnerStatementFiles(arg1:string):Promise<Record<string, any>>;

export function ClearMatchesAndRerun(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function CloseOLEConnection():Promise<Record<string, any>>;

export function CommitReconciliation(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:number):Promise<common.User>;

export function Currency(arg1:number):Promise<string>;

export function Date(arg1:string):Promise<string>;

export function DeleteBankStatement(arg1:string,arg2:string):Promise<void>;

export function DeleteReconciliationDraft(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ExamineOwnerStatementStructure(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ExportNetDistribution(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FollowBatchNumber(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GenerateChartOfAccountsPDF(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GenerateOwnerStatementPDF(arg1:string,arg2:string):Promise<string>;

export function GetAPIKey(arg1:string):Promise<string>;

export function GetAccountBalance(arg1:string,arg2:string):Promise<number>;

export function GetAllRoles():Promise<Array<common.Role>>;

export function GetAllUsers():Promise<Array<common.User>>;

export function GetAuthState():Promise<Record<string, any>>;

export function GetAvailableLocales():Promise<Array<string>>;

export function GetBalanceHistory(arg1:string,arg2:string,arg3:number):Promise<Array<Record<string, any>>>;

export function GetBankAccounts(arg1:string):Promise<Array<Record<string, any>>>;

export function GetBankAccountsForAudit(arg1:string):Promise<Array<Record<string, any>>>;

export function GetBankTransactions(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetCachedBalances(arg1:string):Promise<Array<Record<string, any>>>;

export function GetChartOfAccounts(arg1:string,arg2:string,arg3:boolean):Promise<Array<Record<string, any>>>;

export function GetClosingStatus(arg1:string,arg2:string):Promise<string>;

export function GetCompanies():Promise<Array<company.Company>>;

export function GetCompanyInfo(arg1:string):Promise<Record<string, any>>;

export function GetCompanyList():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDBFFiles(arg1:string):Promise<Array<string>>;

export function GetDBFTableData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetDBFTableDataPaged(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<Record<string, any>>;

export function GetDashboardData(arg1:string):Promise<Record<string, any>>;

export function GetDebugMode():Promise<boolean>;

export function GetLastReconciliation(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetLocale():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetMatchedTransactions(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetNetDistributionStatus(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetOutstandingChecks(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetOwnerStatementData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetOwnerStatementsList(arg1:string):Promise<Array<Record<string, any>>>;

export function GetOwnersList(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetPlatform():Promise<Record<string, any>>;

export function GetRecentBankStatements(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetReconciliationDraft(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetReconciliationHistory(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetTableList(arg1:string):Promise<Record<string, any>>;

export function GetVFPCompany():Promise<Record<string, any>>;

export function GetVFPFormList():Promise<Array<Record<string, string>>>;

export function GetVFPSettings():Promise<Record<string, any>>;

export function GetVendors(arg1:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function ImportBankStatement(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function InitializeCompanyDatabase(arg1:string):Promise<void>;

export function InitializeLogging(arg1:boolean):Promise<Record<string, any>>;

export function LaunchVFPForm(arg1:string,arg2:string):Promise<Record<string, any>>;

export function LoadLocale(arg1:string,arg2:string):Promise<void>;

export function LoadLocalesFromDir(arg1:string):Promise<void>;

export function LogError(arg1:string,arg2:string):Promise<void>;

export function LogMessage(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function Logout(arg1:string):Promise<void>;

export function ManualMatchTransaction(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function MigrateReconciliationData(arg1:string):Promise<Record<string, any>>;

export function Pluralize(arg1:string,arg2:number):Promise<string>;

export function PreloadOLEConnection(arg1:string):Promise<Record<string, any>>;

export function RefreshAccountBalance(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RefreshAllBalances(arg1:string):Promise<Record<string, any>>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ReopenPeriod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestPasswordReset(arg1:string):Promise<void>;

export function ResetPassword(arg1:string,arg2:string):Promise<void>;

export function RetryMatching(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function RunClosingProcess(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Record<string, any>>;

export function RunMatching(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function RunNetDistribution(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Record<string, any>>;

export function SaveReconciliationDraft(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function SaveVFPSettings(arg1:string,arg2:number,arg3:boolean,arg4:number):Promise<void>;

export function SearchDBFTable(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SelectDataFolder():Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetDataPath(arg1:string):Promise<void>;

export function SetDebugMode(arg1:boolean):Promise<Record<string, any>>;

export function SetLocale(arg1:string):Promise<void>;

export function SetOLEIdleTimeout(arg1:number):Promise<Record<string, any>>;

export function SyncVFPCompany():Promise<Record<string, any>>;

export function T(arg1:string,arg2:Array<any>):Promise<string>;

export function TestAPIKey(arg1:string,arg2:string):Promise<boolean>;

export function TestDatabaseQuery(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TestLogging():Promise<string>;

export function TestOLEConnection():Promise<Record<string, any>>;

export function TestVFPConnection():Promise<Record<string, any>>;

export function Translate(arg1:string):Promise<string>;

export function UnmatchTransaction(arg1:number):Promise<Record<string, any>>;

export function UpdateBatchFields(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string,arg5:Record<string, boolean>):Promise<Record<string, any>>;

export function UpdateCompanyInfo(arg1:string):Promise<Record<string, any>>;

export function UpdateDBFRecord(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function UpdateUserRole(arg1:number,arg2:number):Promise<void>;

export function UpdateUserStatus(arg1:number,arg2:boolean):Promise<void>;

export function UpdateVendor(arg1:string,arg2:number,arg3:Record<string, any>):Promise<void>;

export function ValidateGLBalances(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ValidateSession(arg1:string,arg2:string):Promise<common.User>;
