// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuditBankReconciliation(arg1) {
  return window['go']['main']['App']['AuditBankReconciliation'](arg1);
}

export function AuditCheckBatches(arg1) {
  return window['go']['main']['App']['AuditCheckBatches'](arg1);
}

export function AuditSingleBankAccount(arg1, arg2) {
  return window['go']['main']['App']['AuditSingleBankAccount'](arg1, arg2);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function ExportNetDistribution(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportNetDistribution'](arg1, arg2, arg3);
}

export function GetAPIKey(arg1) {
  return window['go']['main']['App']['GetAPIKey'](arg1);
}

export function GetAccountBalance(arg1, arg2) {
  return window['go']['main']['App']['GetAccountBalance'](arg1, arg2);
}

export function GetAllRoles() {
  return window['go']['main']['App']['GetAllRoles']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBalanceHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBalanceHistory'](arg1, arg2, arg3);
}

export function GetBankAccounts(arg1) {
  return window['go']['main']['App']['GetBankAccounts'](arg1);
}

export function GetBankAccountsForAudit(arg1) {
  return window['go']['main']['App']['GetBankAccountsForAudit'](arg1);
}

export function GetCachedBalances(arg1) {
  return window['go']['main']['App']['GetCachedBalances'](arg1);
}

export function GetClosingStatus(arg1) {
  return window['go']['main']['App']['GetClosingStatus'](arg1);
}

export function GetCompanies() {
  return window['go']['main']['App']['GetCompanies']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDBFFiles(arg1) {
  return window['go']['main']['App']['GetDBFFiles'](arg1);
}

export function GetDBFTableData(arg1, arg2) {
  return window['go']['main']['App']['GetDBFTableData'](arg1, arg2);
}

export function GetDBFTableDataPaged(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetDBFTableDataPaged'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function GetNetDistributionStatus(arg1, arg2) {
  return window['go']['main']['App']['GetNetDistributionStatus'](arg1, arg2);
}

export function GetOutstandingChecks(arg1, arg2) {
  return window['go']['main']['App']['GetOutstandingChecks'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RefreshAccountBalance(arg1, arg2) {
  return window['go']['main']['App']['RefreshAccountBalance'](arg1, arg2);
}

export function RefreshAllBalances(arg1) {
  return window['go']['main']['App']['RefreshAllBalances'](arg1);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function ReopenPeriod(arg1, arg2) {
  return window['go']['main']['App']['ReopenPeriod'](arg1, arg2);
}

export function RunClosingProcess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunClosingProcess'](arg1, arg2, arg3, arg4);
}

export function RunNetDistribution(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunNetDistribution'](arg1, arg2, arg3, arg4);
}

export function SearchDBFTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchDBFTable'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function TestAPIKey(arg1, arg2) {
  return window['go']['main']['App']['TestAPIKey'](arg1, arg2);
}

export function UpdateDBFRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDBFRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateUserRole(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserRole'](arg1, arg2);
}

export function UpdateUserStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserStatus'](arg1, arg2);
}

export function ValidateSession(arg1, arg2) {
  return window['go']['main']['App']['ValidateSession'](arg1, arg2);
}
